### ISSUE TITLE
VPC for HL2: Sandbox

### ISSUE THREAD

**Issue by lunar0724** [xXxToxicBlueDustxXx/Half-Life-2-Sandbox-Source-Code#2]
Why aren't there any VPC for HL2: Sandbox. It showed in the Visual Studio 2010 project that the .vpc file was in the project but not located.

**Comment by FriskTheFallenHuman** [comment]
well that file is from valve's internal developtment (see the HL2MP 2007 Code ) but vpc is not used in that branch, just only in internal branchs and code
